#!/bin/sh
### BEGIN INIT INFO
# Provides:		pigpiod
# Required-Start:	$all
# Required-Stop:	$all
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

NAME=pigpiod
DESC="Pi GPIO Daemon"

HELPER=/usr/local/bin/pigpiod
test -x $HELPER || exit 0

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

action="$1"
shift

case "$action" in
  start)
	/usr/local/bin/pigpiod
	;;
  stop)
	killall pigpiod
	;;
  restart)
	$0 stop "$@"
	$0 start "$@"
	;;
  *)
	echo "Usage: /etc/init.d/$NAME {start|stop|restart} [configs]" >&2
	exit 1
	;;
esac

exit 0
