#!/bin/bash

NAME="maypi"                                      # Name of the application
DJANGODIR=/home/maypi/webapp/maypi                # Django project directory
SOCKFILE=/home/maypi/webapp/run/gunicorn.sock     # we will communicte using this unix socket
USER=maypi                                        # the user to run as
GROUP=maypi                                       # the group to run as
NUM_WORKERS=2                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=maypi.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=maypi.wsgi                     # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source $DJANGODIR/../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /usr/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=DEBUG \
  --bind=unix:$SOCKFILE
  #--bind=localhost:8000

